### ISSUE TITLE
potential LGPL license violation

### ISSUE THREAD

**Issue by witten** [kmwoley/onebusaway-pebbletime#4]
The included `math-sll.h` fixed point math library is licensed under the [GNU LGPL](https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-%28lgpl-2.1%29), which stipulates that if the LGPL-licensed code is statically linked, then anything statically linked with it must also be licensed under the LGPL. However, while `math-sll.h` appears to be statically linked with your executable, the rest of your code appears to be Apache-licensed.

One way to fix this would be to build `math-sll.h` separately into a shared library, and then make use of it at runtime, assuming such a thing is possible with the Pebble SDK. If not, then another option would be to switch to another fixed point math library. Yet another option is to re-license your code under LGPL.

**Comment by kmwoley** [comment]
Great catch! 

I chose the Apache license mostly align with the official OneBusAway project, not thinking about the GNU LGPL licensed math-ssl.h. Unfortunately, I don't think I can re-license under LGPL if this code is going to be part of the official OneBusAway project.

I'll look into building math-sll.h as a shared lib. I don't think that's actually a possibility with the Pebble SDK, but I'll go fish. There are other fixed point libraries out there. This is the one recommended by Pebble (since, for some reason, they chose not to make use of the FP unit on the watch hardware, and instead do really bad, code-bloating floating point emulation).

**Comment by witten** [comment]
Ugh, that's obnoxious. Almost seems like a bug that should be filed "upstream" with Pebble themselves. By recommending the library, they're basically recommending the LGPL but perhaps not letting their customers/developers know about the licensing implications.

**Comment by kmwoley** [comment]
An earlier version of this program used libfixmath (https://code.google.com/archive/p/libfixmath/, https://github.com/PetteriAimonen/libfixmath). I can convert back to that library (which utilizes the MIT license) which I believe to be compatible with this project's Apache v2.0 license. 

I also reached out to the OneBusAway team to set they are on using the Apache 2.0 license. If I can put this code under a LGPL-compatible license, that's my preferred approach.

**Comment by kmwoley** [comment]
Alright, so building a static lib isn't that hard... just feel kinda janky.
https://forums.pebble.com/t/can-pebble-access-the-static-c-library/9982

Looks like the steps are:
1) create a separate pebble project for the lib, build the .a there (via modified wscripts, of course)
2) copy the .a / .h files from the lib to your project
3) modify the wcript to include the libs

What I may not be getting is how this satisfies the LGPL requirement. All of the code is in the header, so the LGPL licensed header would still be in my project... the only thing that would change is how the binary is built (include the code from the .a instead of a .o compiled as part of the project).

Does that satisfy the LGPL requirement as far as you know?

Another path is that Pebble now supports packages via npm:
https://developer.pebble.com/guides/pebble-packages/creating-packages/

But it feels odd for me to be the one to create (and maintain?) the math-sll package as a solution to this problem.

**Comment by witten** [comment]
Static linking of any sort won't work.. Only a shared object library (a .so file) will support different licensing according to the LGPL. Given that the math library is just a header, that may mean you'd need to move the implementation of function into a .c file so that what you're including in your application is truly just headers/declarations.

I agree it seems odd for you to have to do any surgery on the math library to make it usable for this. You could try contacting the developers and see if this is something they want to take on.

Also, IANAL.
